### ISSUE TITLE
Error ZHADevice object has no attribute

### ISSUE THREAD

**Issue by DrCoolzic** [dmulcahey/zha-device-exporter#2]
Added zha_device_exporter: in yaml config
FYI Tried to run the service - getting following error:
```
2021-01-09 17:32:26 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: domain=zha_device_exporter, service=export_devices, service_data=>
2021-01-09 17:32:26 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547715041696] 'ZHADevice' object has no attribute 'async_get_info'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1445, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/zha_device_exporter/__init__.py", line 49, in export_devices_handler
    await hass.async_add_executor_job(save_json, file_name, get_devices())
  File "/config/custom_components/zha_device_exporter/__init__.py", line 44, in get_devices
    return [device.async_get_info() for device in zha_gateway.devices.values()]
  File "/config/custom_components/zha_device_exporter/__init__.py", line 44, in <listcomp>
    return [device.async_get_info() for device in zha_gateway.devices.values()]
AttributeError: 'ZHADevice' object has no attribute 'async_get_info'
```

**Comment by nblky** [comment]
how to uesd it  like: 
homeassistant: 
  packages: !include_dir_named zha_device_exporter/
